// user related actions
const LOG_IN = "REDUX_ACTION_LOGIN";
const LOG_OUT = "REDUX_ACTION_LOGOUT";

// list related actions
const FETCH_LIST = "REDUX_ACTION_FETCHLIST";
const ADD_TO_LIST = "REDUX_ACTION_ADD_TO_LIST";
const UPDATE_IN_LIST = "REDUX_ACTION_UPDATE_IN_LIST";
const REMOVE_FROM_LIST = "REDUX_ACTION_REMOVE_FROM_LIST";
const ADD_SAFETY_GROUP_TO_TRUCK = "REDUX_ACTION_ADD_SAFETY_GROUP_TO_TRUCK"
const ADD_MULTIPLE_SAFETY_GROUP_TO_TRUCK = "REDUX_ACTION_ADD_MULTIPLE_SAFETY_GROUP_TO_TRUCK"

// po related actions
const FETCH_PO = "REDUX_ACTION_FETCH_PO";
const ADD_TO_PO = "REDUX_ACTION_ADD_TO_PO";
const UPDATE_IN_PO = "REDUX_ACTION_UPDATE_IN_PO";
const REMOVE_FROM_PO = "REDUX_ACTION_REMOVE_FROM_PO";

// maintenance form related actions
const FETCH_FB = "REDUX_ACTION_FETCH_FB";
const ADD_FB = "REDUX_ACTION_ADD_FB";
const UPDATE_FB = "REDUX_ACTION_UPDATE_FB";
const REMOVE_FB = "REDUX_ACTIOB_REMOVE_FB";

// customers
const FETCH_CUSTOMER = "REDUX_ACTION_FETCH_CUST";
const ADD_CUSTOMER = "REDUX_ACTION_ADD_TO_CUST";
const UPDATE_CUSTOMER = "REDUX_ACTION_UPDATE_CUST";
const ADD_CUSTOMER_BILLING_LOCATION = "REDUX_ACTION_ADD_CUST_BILL_LOC";
const UPDATE_CUSTOMER_BILLING_LOCATION = "REDUX_ACTION_UPDATE_CUST_BILL_LOC";
const ADD_CUSTOMER_CONTACTS = "REDUX_ACTION_ADD_CUST_CONTACT";
const UPDATE_CUSTOMER_CONTACTS = "REDUX_ACTION_UPDATE_CUST_CONTACT";

//safety and compliance
const FETCH_SAFETY = "REDUX_ACTION_FETCH_SAFETY"
const ADD_SAFETY = "REDUX_ACTION_ADD_SAFETY"
const UPDATE_SAFETY = "REDUX_ACTION_UPDATE_SAFETY"
const FETCH_SAFETY_GROUP = "REDUX_ACTION_FETCH_SAFETY_GROUP"
const ADD_SAFETY_GROUP = "REDUX_ACTION_ADD_SAFETY_GROUP"
const UPDATE_SAFETY_GROUP = "REDUX_ACTION_UPDATE_SAFETY_GROUP"

module.exports = {
  LOG_IN,
  LOG_OUT,

  FETCH_LIST,
  ADD_TO_LIST,
  UPDATE_IN_LIST,
  REMOVE_FROM_LIST,
  ADD_SAFETY_GROUP_TO_TRUCK,
  ADD_MULTIPLE_SAFETY_GROUP_TO_TRUCK,

  FETCH_PO,
  ADD_TO_PO,
  UPDATE_IN_PO,
  REMOVE_FROM_PO,

  FETCH_FB,
  ADD_FB,
  UPDATE_FB,
  REMOVE_FB,

  // customer
  FETCH_CUSTOMER,
  ADD_CUSTOMER,
  UPDATE_CUSTOMER,
  ADD_CUSTOMER_BILLING_LOCATION,
  UPDATE_CUSTOMER_BILLING_LOCATION,
  ADD_CUSTOMER_CONTACTS,
  UPDATE_CUSTOMER_CONTACTS,

  //safety and coompliance
  FETCH_SAFETY,
  ADD_SAFETY,
  UPDATE_SAFETY,
  FETCH_SAFETY_GROUP,
  ADD_SAFETY_GROUP,
  UPDATE_SAFETY_GROUP
};
